### ISSUE TITLE
ngettext with a regular sting

### ISSUE THREAD

**Issue by uladzimirdev** [ttag-org/ttag#281]
Hi, I couldn't find the answer from the code, so maybe you can help me to understand how to handle such simple case

```
ngettext(msgid`record`, "records", n);
```

babel plugin doesn't like such strings and raises an error 

```
at template2Msgid (/node_modules/babel-plugin-ttag/dist/utils.js:116:32)
at /node_modules/babel-plugin-ttag/dist/extractors/ngettext.js:55:38
```

is it a bug or just unexpected usage? is there any workaround?

**Comment by AlexMost** [comment]
Hi, seems like a bug, that should work. As a temporary workaround try to use 

```js
ngettext(msgid`record`, `records`, n);
```

The most frequent case for ngettext is when `n` is present in the translated string like

```js
ngettext(msgid`${ n } record`, `${ n } records`, n);
```

But I agree that your example should also work fine. Will take a look at this case ASAP.

**Comment by uladzimirdev** [comment]
fair enough, I had this problem only because of eslint quotes rule, which replaced backticks with double quotes as there wasn't any parameter inside.

Thanks for confirming
